### ISSUE TITLE
Is this module still supported?

### ISSUE THREAD

**Issue by agb80** [collective/templer.buildout#2]
We are looking for a way to distribute our buildout recipe templates and found this project but wonder if is still active and if plone community still uses like a tool, we don't want to start using an abandoned tool that force us to be the only maintainers.

**Comment by gforcada** [comment]
As long as it works for you it is there to be used, if you already know some shortcomings of it, I would recommend to move to [mr.bob](https://pypi.python.org/pypi/mr.bob) (https://github.com/domenkozar/mr.bob) and [bobtemplates.plone](https://pypi.python.org/pypi/bobtemplates.plone) (https://github.com/plone/bobtemplates.plone/) if you need to create plone packages as well.

**Comment by agb80** [comment]
Thanks @gforcada that was my question, will study mr.bob
